### ISSUE TITLE
register to npm

### ISSUE THREAD

**Issue by etylsarin** [noh4ck/redux-swagger-client#1]
seems to me that the module is not registered yet. The registry.npmjs.org returns 404.

Would be also great if you can share some example app to see how to use fetched data in a component.

**Comment by Nohac** [comment]
Sorry, this package is very new and I haven't had time to properly test it yet, I will try to publish it when I feel it's ready and also add more examples.
In the meantime, I can update the installation guide to explain how to install and use it right now.

**Comment by etylsarin** [comment]
ok, I see. I had no problem to install it directly from github, just saying as you have npm isntall in your guidelines. Would be great if you can provide me with some gist of how to use the fetched data as I'm a newbie in term of redux/swagger. :)

**Comment by Nohac** [comment]
Using this should be pretty easy if you understand redux, so I'd recommend you read the [redux documentation](http://redux.js.org/) first. Don't hesitate to ask more questions if it's still unclear.

**Comment by etylsarin** [comment]
ok, cheers, will do.

**Comment by UmaGovindaraj** [comment]
i am getting api is undefined when i use the below code.

swagger: api => api.pet.findPetsByStatus({status: 'available'})

can u pls help me ?
