### ISSUE TITLE
Error due to missing "type" property

### ISSUE THREAD

**Issue by miguelduarte42** [noh4ck/redux-swagger-client#4]
Hi,

I'm getting the following error:

```
Uncaught Error: Actions may not have an undefined "type" property. Have you misspelled a constant?
```

Can this be related to the redux version? I'm on 3.6.0.

Also, if I had a dummy type, it will dispatch the action, make the call to the swagger API, but then no follow-up action will be dispatched from the redux-swagger-client library.

Any idea of what it could be? Here's some of my code:

```
const store = createStore(
  rootReducer,
  undefined,
  compose(
    applyMiddleware(
      thunkMiddleware,
      swaggerClient({url: 'MY_URL'}),
      loggerMiddleware,
      routerMiddleware(history)
    ),
    autoRehydrate()
  )
);




export function fetchSpecialties() {
  return {
    types: ["FETCH_SPECIALTIES", "FETCH_SPECIALTIES_SUCCESS", "FETCH_SPECIALTIES_FAILED"],
    swagger: (api) => api.Specialties.getSpecialties()
  }
}


dispatch(fetchSpecialties());
```

**Comment by Nohac** [comment]
I wish I could be of any help, but I haven't tested the latest version of this myself as I'm not really using this anymore. @Sigura Do yo have any suggestions?

**Comment by Sigura** [comment]
@noh4ck  I guess `./lib` contains old version of `index.js`

**Comment by Sigura** [comment]
I guess PR #5 will fix it.

**Comment by Nohac** [comment]
@Sigura Thanks! 
@miguelduarte42 Hope PR #5 resolved the issue for you!

**Comment by miguelduarte42** [comment]
Thanks for the quick changes @Sigura. I have installed the latest version and now it's breaking the whole project, I am getting the following error:

``
TypeError: (intermediate value).then is not a function
``

This is showing up on line 40 of lib/index.js:

```
  37 |   responseInterceptor: function responseInterceptor(resp) {
  38 |     return !!opts.responseInterceptor ? opts.responseInterceptor(resp, action) : resp;
  39 |   }
> 40 | })).then(function (result) {
  41 |   var swagger = action.swagger,
  42 |       types = action.types,
  43 |       rest = _objectWithoutProperties(action, ['swagger', 'types']);
```

Am I doing something wrong?

**Comment by Sigura** [comment]
I'm not sure but looks like update swagger-client to 3.0.3 needed PR #6

**Comment by Sigura** [comment]
@miguelduarte42 works for me, could you check it?

```
npm i -S noh4ck/redux-swagger-client
```

**Comment by miguelduarte42** [comment]
@Sigura it worked! Fantastic work, thank you for taking the time to look into it!

**Comment by Sigura** [comment]
@miguelduarte42 np ,) have a nce day!
