### ISSUE TITLE
Please republish it on npmjs

### ISSUE THREAD

**Issue by Sigura** [noh4ck/redux-swagger-client#7]
I cannot (

> you do not have permission to publish "redux-swagger-client". Are you logged in as the correct user? : redux-swagger-client

**Comment by Nohac** [comment]
I can't do it either as some random guy published it on npmjs: https://www.npmjs.com/package/redux-swagger-client
I can email him and ask him to give me permission.

**Comment by Sigura** [comment]
I think it's good idea ,)

**Comment by odeann** [comment]
@noh4ck Haven't @casesandberg answered yet? I really like your package and would like to see it on npm updated.

**Comment by Nohac** [comment]
The newest version 2.1.1 is now published to npmjs.com
